### PR TITLE
Add vim syntax file

### PR DESCRIPTION
**Pull request by marekmaskarinec**

### CODE REVIEW

**Comment by marekmaskarinec** [comment]
Should I close this pr because of the comment, or should I keep it?

**Comment by vtereshkov** [comment]
I think we already have that comment. Is it a duplicate? A Vim syntax file is a nice thing for some people (not for me, so I just believe you that it works :) )

**Comment by marekmaskarinec** [comment]
Now, that I think about it, I'm a bit worried about copyright or something, since I just replaced stuff in go syntax file. I credited the author, but I'm not sure if that's enough.

**Comment by marekmaskarinec** [comment]
I will close this. I should make this into a vim module and not just a standalone file.

**Pull request closed without merging**
