### PR TITLE
Optimize conditional jumps (#290)

### PR DESCRIPTION
**Pull request by skejeton**

### CODE REVIEW

**Comment by vtereshkov** [comment]
@skejeton Thank you. At first glance, it seems viable. I'll try to merge your changes into a separate branch, test them and then merge to `master`.

If everything goes well, we can think of whether we can use the same new instruction in the `for` statement.

**Comment by vtereshkov** [comment]
Oh, it went directly to `master`. OK, let's see.

**Comment by skejeton** [comment]
I tried to implement it for `for`, but it's not possible since if we do this:
```
init...
cond...
goto_if_not end
statement...
goto cond
code...
goto statement
end...
```
Then the statement will execute after the condition if the `goto_if_not` isn't met, we'll need to somehow generate the statement before the condition, then indeed we can get rid of a bunch of GOTO's, but it's hard with the current parser.

**Comment by vtereshkov** [comment]
@skejeton Did you run the tests? They fail for me:
```
Runtime error C:/Users/vtere/Desktop/umka-lang/tests/dynarrays2.um (34): Incompatible types void and bool in printf()
Stack trace:
    test2: C:/Users/vtere/Desktop/umka-lang/tests/dynarrays2.um (34)
    test: C:/Users/vtere/Desktop/umka-lang/tests/dynarrays2.um (44)
    main: C:/Users/vtere/Desktop/umka-lang/tests/all.um (49)
    <unknown>: C:/Users/vtere/Desktop/umka-lang/tests/all.um (86)
```
And I can guess what it means: a problem with `doDynArrayToDynArrayConv()`.

Reverting unless fixed.

**Pull request merged**
