### PR TITLE
umka syntax highlighter

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
I create a non complete nanorc file for umka

### CODE REVIEW

**Comment by vtereshkov** [comment]
@PooiaFerdowsi I think you should at least add the syntax highlighting for string/character literals and comments.

**Comment by marekmaskarinec** [comment]
I tried adding some stuff and this is, what I ended up with:
```
# Umka for Gnu nano

syntax "Umka" "\.um$"
comment "//"

color brightblue "\<(break|case|const|continue|default|else|for|fn|import|interface|if|in|return|str|struct|switch|type|var|weak)\>"

#color red "\<(+|\-|\*|/|%|&|\||~|<<|>>|\+=|\-=|\*=|/=|%=|&=|\|=|~=|<<=|>>=|&&|\|\||!|\++|\--|==|<|>|!=|<=|>=|=|:=)\>"

color yellow ""(\\.|[^"])*"|'(\\.|[^'])*'"
color yellow   "`[^`]*`"

color cyan "TODO|XXX|FIXME"

color brightwhite "\<(\(|\)|\[|\]|\{|\}|\^|;|:|.)\>"

color green "\<(true|false|null)\>"

color brightyellow "\<(void|int8|int16|int32|int|uint8|uint16|uint32|uint|bool|char|real32|real|fiber)\>"

color magenta "repr|round|trunc|fabs|sqrt|sin|cos|atan|exp|log|fiberspawn|fibercall|printf|atan2|fiberalive"

color brightgreen "\<([0-9]+|0x[0-9a-fA-F]*)"

# this doesn't show for me, but I don't know, what color to use.
color brightblack "//.*"
color brightblack start="^\s*/\*" end="\*/"
```
Screenshot:
2021-05-01-125855_1048x862_scrot

Comments are currently implemented, but `brightblack` doesn't show up for me. Any idea, what to put there?

**Comment by PooiaFerdowsi** [comment]
> @PooiaFerdowsi I think you should at least add the syntax highlighting for string/character literals and comments.

Okay :ok: I add the strings & comments in 24H later .
after send this comment

**Comment by marekmaskarinec** [comment]
@PooiaFerdowsi 

The one, I sent already has strings and comments implemented. Please figure out, what color to use for comments.

**Comment by PooiaFerdowsi** [comment]
I added

**Comment by PooiaFerdowsi** [comment]
> @PooiaFerdowsi
> 
> The one, I sent already has strings and comments implemented. Please figure out, what color to use for comments.

I'm not english , I don't understand your mean , can you say with another style

**Comment by PooiaFerdowsi** [comment]
> @PooiaFerdowsi
> 
> The one, I sent already has strings and comments implemented. Please figure out, what color to use for comments.

Yes I understand . I changed it

**Pull request closed without merging**
