### PR TITLE
boolean unsupported in very C compiler

### PR DESCRIPTION
**Pull request by PooiaFerdowsi**
c don't have booleans but C++ have bool

### CODE REVIEW

**Comment by vtereshkov** [comment]
Umka source is written in C99, where `bool`, `true` and `false` are standard. What compiler are you using? Anyway, it seems strange that you replace `true` and `false` with `1` and `0` in `umka_lexer.c` but not in all other files.

**Comment by PooiaFerdowsi** [comment]
I am using gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

I don't can see and change in project over 30 file & over 1000*15 lines code

**Comment by marekmaskarinec** [comment]
You can do it using: `sed -i 's/false/0/g' *.c`, `sed -i 's/true/1/g' *.c` and `sed -i 's/bool/char/g' *.c`. @vtereshkov should I make a pr with all these changes, or do you want to keep using bools?

**Comment by vtereshkov** [comment]
@PooiaFerdowsi I cannot understand the problem. Does `./build_linux.sh` fail? If it does, what error message does it print? I have never had any problems running it on Ubuntu.

@marekmaskarinec Let's wait for a clarification of the problem.

**Comment by marekmaskarinec** [comment]
Btw, try adding `-std=c99` to force gcc to use c99.

**Comment by PooiaFerdowsi** [comment]
no -std=c99 don't work
@vtereshkov my build was successfull
also better is i create an issues 
Ok! I close this PULL REQUEST by comment

**Pull request closed without merging**
