### PR TITLE
add `std.fflush`

### PR DESCRIPTION
**Pull request by thacuber2a03**
this PR was made to "complete" #324 by adding file flushing so the input/output/error streams don't need to wait for a newline to be emitted or the application to end to write to the console.
I tried to add only as much as needed for the behavior to work and to not change a lot of files, as this is my first "complex" PR and I don't know a lot about the structure of the repository.
it could be argued that `build_playground_linux.sh` and `run_emscripten_linux.sh` were not needed, but I wanted to make it easy to compile the playground for Linux users. said behavior could be added to the Makefile too, so that doing something such as `make playground` would be enough to build it.

### CODE REVIEW

**Review by vtereshkov — CHANGES_REQUESTED** [review]
1. Do you know any practical use cases for `fflush()`?
2. Did you test your changes, including the playground build script for Linux?
3. It seems that you haven't updated the playground after your follow-up commits. Please update it.

**Comment by thacuber2a03** [comment]
1) I mentioned two of them above
2) yes, I have, I built the playground using that same Linux build script :sweat_smile:
3) oh, ok, give me a second

**Comment by thacuber2a03** [comment]
> 1. I mentioned two of them above

actually, I only mentioned one, but another use case would be to make sure all changes to a file actually save before closing it

**Comment by marekmaskarinec** [comment]
I think `fclose` should handle that for you. At least the manpages on
my system are saying so.

**Comment by thacuber2a03** [comment]
> I think `fclose` should handle that for you. At least the manpages on my system are saying so.

oh, yeah, it does here :/

**Comment by thacuber2a03** [comment]
well, in the case that this PR doesn't get merged, would it be nice to implement the ability to build the playground and/or releases through `make`? (in a separate PR, of course :sweat_smile:)

**Comment by vtereshkov** [comment]
@thacuber2a03 I know of one problem that hopefully can be solved with `fflush()`. The web playground's `printf()` prints anything only after a `\n` is received. So, `printf("Hello, World!")` does nothing visible until you print a `\n` later. Can it be fixed by calling `std.flush(std.stdout())`?

**Comment by vtereshkov** [comment]
@marekmaskarinec Nevertheless, do you find it useful to have `fflush()` in Umka?

**Comment by thacuber2a03** [comment]
> @thacuber2a03 I know of one problem that hopefully can be solved with `fflush()`. The web playground's `printf()` prints anything only after a `\n` is received. So, `printf("Hello, World!")` does nothing visible until you print a `\n` later. Can it be fixed by calling `std.fflush(std.stdout())`?

I'd have to make `fflush` work in both the playground and sandbox modes to at least try that, because right now it does nothing when the sandbox flag is enabled:
```c
void rtlfflushSandbox(Slot *params, Slot *result)
{
    result->intVal = EOF;
}
```

**Comment by vtereshkov** [comment]
> well, in the case that this PR doesn't get merged, would it be nice to implement the ability to build the playground and/or releases through make? (in a separate PR, of course 😅)

Maybe. I personally don't like `make` because my main development platform is Windows, where there is no "standard" `make`, so I only rely on 100 % standard tools, such as `cmd.exe` and `sh`. 

However, it would be great to have a full-scale CI for Umka, not just some test builds for Linux. In other words, I'd like to have the same builds as generated by the `build*.bat` and `build*.sh` scripts, but deployed automatically. See also https://github.com/vtereshkov/umka-lang/issues/319.

**Comment by thacuber2a03** [comment]
> Maybe. I personally don't like `make` because my main development platform is Windows, where there is no "standard" `make`, so I only rely on 100 % standard tools, such as `cmd.exe` and `sh`.
> 
> However, it would be great to have a full-scale CI for Umka, not just some test builds for Linux. In other words, I'd like to have the same builds as generated by the `build*.bat` and `build*.sh` scripts, but deployed automatically. See also #319.

that would be nice, although I've never set up CI in any of my projects so I can't really help with that, sorry

**Comment by vtereshkov** [comment]
@thacuber2a03 I think `fflush()` should work with `stdout` even in the sandbox mode, so we can remove the `rtlfflushSandbox()` stub.

On the other hand, I see the
```
    if f == null {
        error("File is null")
    }
```
check is missing from your `std.fflush()` implementation. Please add it.

**Comment by marekmaskarinec** [comment]
> @marekmaskarinec Nevertheless, do you find it useful to have fflush() in Umka?

Personally, I don't find `fflush` all that useful except for some very rare uses. I think it shouldn't be part of `std.um` (which from what I understand you want to keep small and simple). However, I'd be happy to add it to `os.um`.

**Comment by thacuber2a03** [comment]
> @thacuber2a03 I know of one problem that hopefully can be solved with `fflush()`. The web playground's `printf()` prints anything only after a `\n` is received. So, `printf("Hello, World!")` does nothing visible until you print a `\n` later. Can it be fixed by calling `std.fflush(std.stdout())`?

after a bunch of tries, I'm sorry to announce it doesn't seem to work :(

**Comment by thacuber2a03** [comment]
> Personally, I don't find `fflush` all that useful except for some very rare uses. I think it shouldn't be part of `std.um` (which from what I understand you want to keep small and simple). However, I'd be happy to add it to `os.um`.

there's an `os.um` library?

**Comment by vtereshkov** [comment]
@thacuber2a03 Could you please commit the changes to your `master` so I could download and check them myself? If the playground problem isn't fixed, I think we need some other justification for including `fflush()`. Can you provide some code snippet or anything else that shows some problem solved by `fflush()`?

**Comment by vtereshkov** [comment]
@thacuber2a03 The playground problem isn't fixed for me either. Any other demonstrable use cases?

**Comment by thacuber2a03** [comment]
I think I just found an oddball:
```umka
import "std.um"

fn main() {
	flush := std.argc() > 1
	for i := 0; i < 10; i += 1 {
		std.fwrite(std.stdout(), []char(sprintf("test %i ", i)))
		if flush { std.fflush(std.stdout()) }
		std.fwrite(std.stderr(), []char(sprintf("stderr test %i\n", i)))
	}
}
```
console output:
```shell
thacuber2a03@a-linux-pc:~/Documentos/gitclones/umka-lang-tc$ umka test.um
stderr test 0
stderr test 1
stderr test 2
stderr test 3
stderr test 4
stderr test 5
stderr test 6
stderr test 7
stderr test 8
stderr test 9
test 0 test 1 test 2 test 3 test 4 test 5 test 6 test 7 test 8 test 9 thacuber2a03@a-linux-pc:~/Documentos/gitclones/umka-lang-tc$ umka umka test.um flush
test 0 stderr test 0
test 1 stderr test 1
test 2 stderr test 2
test 3 stderr test 3
test 4 stderr test 4
test 5 stderr test 5
test 6 stderr test 6
test 7 stderr test 7
test 8 stderr test 8
test 9 stderr test 9
thacuber2a03@a-linux-pc:~/Documentos/gitclones/umka-lang-tc$ 
```

**Comment by thacuber2a03** [comment]
@vtereshkov smplifying the snippet above ends with:
```umka
import "std.um"

fn main() {
	flush := std.argc() > 1
	for i := 0; i < 10; i += 1 {
		fprintf(std.stdout(), "test %i ", i)
		if flush { std.fflush(std.stdout()) }
		fprintf(std.stderr(), "stderr test %i\n", i)
	}
}
```

**Comment by thacuber2a03** [comment]
the only other way I could think of making it useful is if there was a way to change the buffering mode of any file/input stream, but I feel that would be bloat at this point :(

**Comment by vtereshkov** [comment]
@thacuber2a03 On Windows, there is no difference between the flushed and non-flushed runs. On Linux, I see the same effect as you.

**Comment by marekmaskarinec** [comment]
> there's an os.um library?

Yes. It's available through the new UmBox package manager: https://umbox.tophat2d.dev/package/os

**Pull request merged**
