### PR TITLE
Parse octal and binary numbers

### PR DESCRIPTION
**Pull request by skejeton**
Support for octal and binary numbers in lexer

### CODE REVIEW

**Review by vtereshkov — CHANGES_REQUESTED** [review]
The task is harder than it may seem:
* `string[1]` and `string[2]` are not guaranteed to exist. This may cause a segmentation fault.
* What happens if an octal number is followed by a fractional part or an exponent? WIll the fractional part still be decimal? This issue probably exists even in the current implementation.
* Rename `parseInt` into `lexInt` as it is a part of the lexer, not the parser.
* Declare `lexInt` as static.

**Comment by iotasieve** [comment]
I have a question though, shouldn't 
```
    if (tail == lex->buf + lex->bufPos && ch != '.')
    {
        lex->tok.kind = TOK_NONE;
        return;
    }


```
be
```    
    if (tail == lex->buf + lex->bufPos && ch != '.')
    {
        lex->error->handler(lex->error->context, "Empty number");
        return;
    }

```

**Comment by vtereshkov** [comment]
I think this doesn't matter. If you return `TOK_NONE`, you'll eventually get the `Unexpected character or end of file` error. 

I even think that this code is unreachable, since I call `lexNumber()` if and only if I know that the current character is a digit or a dot.

**Comment by vtereshkov** [comment]
It's a nice idea to have a function that detects the base. But, frankly speaking, the implementation could be much more elegant if you carefully use `lexChar()`. You could get rid of `Base` and return just an `int`, that is, the base. The only difficult special case is the exact 0, when the number itself should not be parsed (there is nothing after the 'octal prefix').

**Comment by iotasieve** [comment]
I have considered that solution, but multiple notations for octal numbers do not allow for base to be detected that way (Unless I misunderstood your idea), there's str_offset that indicates offset for the actual content of the number. I think the current way of returning a Base struct is fine. The edge case of 0 (and it's fractions) is covered as well in this implementation.

**Comment by iotasieve** [comment]
Bumping the thread, also noting that I don't see how `lexChar` could help us in that scenario, this would allow for numbers to be separated with newlines, as for implementation of `lexChar`. Which is potentially bad, because if hexadecimal number is newlined, it could be an identifier, but lexer will mistake it (although I'm sure that scenario is very unlikely). 

```c
static char lexChar(Lexer *lex)
{
    char ch = lex->buf[lex->bufPos];
    if (ch)
    {
        lex->bufPos++;
        lex->pos++;
        if (ch == '\n')
        {
            lex->line++;
            lex->debug->line++;
            lex->pos = 1;
        }
    }
    return lex->buf[lex->bufPos];
}
```

**Pull request closed without merging**
