### PR TITLE
FInal GitActions

### PR DESCRIPTION
**Pull request by skaller**
Given up on Windows. Changed so Git Actions uses GithubActionsMain.mak to avoid 
conflict with any make files or scripts.

If implemented, make sure to remove or change the badge in README.md.
This clone will be deleted after the PR is merged.

### CODE REVIEW

**Comment by vtereshkov** [comment]
I think I cannot merge this for two reasons:
* Some people would like to call just `make` rather than `make -f GithubActionsMain.mak`.
* The Windows build stub can be useful for the future contributors. Anyway, I personally never use `make` on Windows, so this does not affect my habits.

Your previous commits are on `master`. Now I will delete the `visibility-control` branch.

**Comment by skaller** [comment]
I deliberately changed it so that it didn't interfere with any makefiles you want. You can always copy it.
I do not use make (except as a top level dispatcher) on any platforms.  I put the GithubActions in purely
to prove that the visibility control does not break anything. Also a learning experience for me.
I cannot use Umka without suitable visibility controls and given it is still actively developed
I want to be able to include the whole repository easily in Felix, and be able to upgrade it
just as easily. Anyhow, the next thing is an init with a string: the file based init is a good
way for a standalone executable but useless for embedding.

**Comment by vtereshkov** [comment]
@skaller I think it is a rather strange requirement for a third-party project to have any specific file names so that you can integrate it with Felix. I see no reason for having two identical makefiles, one for you and one for all other people.

Reading the source from a string buffer has already been implemented. See the updated language reference and the `umka_api.h` header.

**Comment by skaller** [comment]
I think I did not explain myself. I used the `*.mak` makefile names so that *you* remained free to implement makefiles as *you* choose whilst retaining the ability to use GithubActions to run continuous integration tests, whilst those files were provided in the first place solely to demonstrate the operation of the visibility controls did not break anything.

Felix will not be using any of the scripts, makefiles, or anything at all other than `*.h`, `*.c`, and perhaps `*.um` sourcefiles. 

The only requirement is that the visibility macros can be set by the Felix build system so as to produce a shared and static library that works on all platforms Felix supports. Unless the `UMKA_EXTERN` macro is provided in the API source `umka_api.h` I would have to edit that file in order to support `umka`, and would then have to edit it manually again, every time I pulled it from the upstream master. I do not wish to do that.

There is nothing Felix specific in what I implemented: the visibility controls are *required* on Windows using MSVC,  are recommended on all Unix platforms, and very strongly recommended on all modern Unix platforms including MacOS and Linux. 

FYI: Not everyone follows the recommendations. Python devs made a specific and considered decisions *not* to use two level namespaces on Linux, to allow legacy CPython C extensions to continue to run, which breaks the ability of Felix to host Python on Linux if the Python happens to use other CPython extensions. It pains me but Python is a mess anyhow,  many operations are not re-entrant.

**Comment by vtereshkov** [comment]
As you can see from the current state of the `master` branch, the `UMKA_API` (former `UMKA_EXTERN`) constant has been merged there from your previous commits, so that you can freely use it.

**Pull request closed without merging**
