### PR TITLE
Intercepting `std.exitif` (vtereshkov#368)

### PR DESCRIPTION
**Pull request by skejeton**

### CODE REVIEW

**Review by vtereshkov — COMMENTED** [review]
@skejeton What does it print when called from the standalone Umka? Two different stack traces?

**Comment by skejeton** [comment]
Maybe it's better to leave it up to the program to print the stack trace?

**Comment by vtereshkov** [comment]
Do you mean the host program? Maybe. Do you think it's a lesser evil for now to sometimes have two stack traces than to have none?

**Comment by skejeton** [comment]
In my opinion - none. The C code using Umka should decide if to print a stack trace or not. Still having access to stack trace via Umka is also important, for example in SaveScum I have a resource loader, and with the trace information I can get the exact line and file where that resource failed to load. Just one of the examples.

**Comment by vtereshkov** [comment]
A proposal:
```
    Err* = struct {
        code: int
        msg: str
        sender: any
        forward: bool
        trace: []ErrPos
    }
```
If `forward == true`, the error message is forwarded to C via `exit()` (as in your PR). Otherwise, it is printed immediately and not passed to `exit()`.

**Comment by skejeton** [comment]
@vtereshkov I'm not sure about bloating the error structure to be honest, but I would add it as a parameter to `exitif`

**Comment by vtereshkov** [comment]
`fn exitif*(err: Err, forward: bool = false)`? Agree. Far from perfect, but, again, better than nothing if you really need this feature.

For me, using Windows message boxes for something longer than one sentence is weird, but it's up to you.

image

**Comment by skejeton** [comment]
This one is actually unintended, it happens because `th_info` shows a `MessageBox` when tophat is in Windows subsystem (console disabled). It should ideally open a browser or notepad but that'll take some work, so right now it stays unfixed.

**Comment by skejeton** [comment]
Hmm `forward` parameter is still not as good IMO, because I'll always need to manually pass `true` to it, and so if my program crashes anytime, it will close without any error message popping up. I still think we should transfer this control to the C code. @marekmaskarinec What do you think?

**Comment by vtereshkov** [comment]
@skejeton 

>  I'll always need to manually pass true to it

Yes, you will. My idea with adding `forward` as a field to `std.Err` was an attempt to avoid this. But it seems that the net effort would be the same.

> if my program crashes anytime, it will close without any error message popping up

What do you mean? A true crash (like dereferencing a null pointer) will always be forwarded to C.

**Comment by skejeton** [comment]
`std.Err` will still have the same issue, just that before calls to `exitif` you'll need to assign the `forward` flag. To explain the problem with `std.exitif` in tophat right now, if the program is compiled without a console window for Windows, the game will close without output to the stdout/stderr (since it's not a console app), and without a MessageBox (the `exit` call in `exitif` has no message, so tophat doesn't show the error message box). So it happens that all these assertions with `exitif` show no indication of when, where and what happened, the program just closes. This can be solved by using `exitif` as a wrapper and letting the C user code handle the runtime error, so there's more flexibility on what to do with the call. Maybe I'm misunderstanding the point of this function, is this function intended purely for the user to see the stack trace? I'm a bit confused about it's purpose but the Tophat problem needs to be solved one way or the other.

**Comment by vtereshkov** [comment]
@skejeton I understand the problem you're trying to solve, but don't see why adding the `forward` flag (to either `std.Err` or `std.exitif()`) cannot help. Do you think it will not work? Or will just be not very convenient?
```
fn exitif*(err: Err, forward: bool = false) {
    if err.code != 0 {
        s := sprintf("Runtime error: %s (code %d) in %v\n", err.msg, err.code, err.sender)
        s += sprintf("Stack trace:\n")
        for _, pos in err.trace {
            s += sprintf("    %s: %s (%d)\n", pos.func, pos.file, pos.line)
        }
        if forward {
            exit(err.code, s)   // printed by Tophat and/or displayed in a message box 
        } else {
            printf("%s", s)     // printed immediately
            exit(err.code) 
        }
    }    
}
```

**Comment by skejeton** [comment]
@marekmaskarinec need to weigh in.

**Comment by marekmaskarinec** [comment]
Personally, I don't think this is an issue that needs solving. By design `exitif` is only supposed to be called from application code - a library should never, under any circumstances exit the application. For this reason, it is not necessary to alter the standard `exitif` to tophat's needs. We can just make our own `th.exitif` and instruct people to use that.

But as far as your solution goes, I think `forward` is better at the exitif level. But I still think it's unnecessarily complicated.

**Comment by skejeton** [comment]
`exitif` is never called in tophat's library itself, since tophat is 
supposed to return error codes. So `exitif` is only used in usage code, 
the problem is that it will be rather confusing that an `exitif` doesn't 
show the error message passed to it, just silently exits the program 
with the given error code. This is only present in Windows subsystem 
builds, since it has the console disabled.

Maybe @marekmaskarinec can weigh in?

**Comment by marekmaskarinec** [comment]
Users will be instructed to use `th.exitif` instead of `std.exitif`.

**Comment by skejeton** [comment]
Seems rather half baked to me...

**Comment by marekmaskarinec** [comment]
But I think that's kind of the point of `std.exitif`. It's just some kind of default way to crash on error. In reality, every application would probably handle this themselves.

**Comment by skejeton** [comment]
I think I'm misunderstanding the purpose of this function. What is the 
benefit to printing it out to the stdout? With the default Umka 
interpreter shell (umka.c) this would be already the case, if it was 
just an error message passed to `exit`, wouldn't it?

**Comment by marekmaskarinec** [comment]
I think the function is ok as the default handler, but it doesn't fit all uses. Yes, the tophat use case might be fixed by adding a forward flag, but what if the application wants to, for example, log it to a file and then call some other cleanup functions? I think we should just embrace creating your own exitif function if needed.

**Comment by skejeton** [comment]
That's true, although there's some functions within the `std` I asked 
for that are kind of completely useless for me, since they use `exitif` 
inside. For example the `assert` function.

If `exitif` is indeed the default handler for errors, then in my opinion 
it should also be possible to intercept the error from it.

An alternative, maybe compromise solution I can think of is being able 
to override the `std.exitif` handler, similar to signal handlers in C. 
For example by using `std.onsignal(.error, fn (prev: std.SignalHandler) 
{ })`. Or something along this way.

If not this then in this PR I'm going to at least change `printf` to 
`fprintf(stderr` since it doesn't make sense to output errors into 
`stdout`. If we settle on this, then I think we'll need to return to 
this issue later, doesn't feel very complete to me, and for the time 
being I'll return to using my own `assert` function and my own error 
handler.

**Comment by vtereshkov** [comment]
@skejeton 

If adding the `forward` flag can relieve your pain, I'm OK with it. Will you also need it in `std.assert()`?

`std.onsignal()` seems to be too complicated.

The errors are printed to `stdout` because my playground now disables all explicit file I/O, even if the file is just `stderr`.

**Comment by skejeton** [comment]
> The errors are printed to `stdout` because my playground now disables all explicit file I/O, even if the file is just `stderr`.

Understandable, maybe one of us should create an issue.

I still don't exactly understand why keeping the default handler output to `stdout` is better than passing it to `exit`, giving more flexibility, but I think we'll return to this issue eventually.

I don't really like the `forward` flag solution, so this can be closed.

**Comment by vtereshkov** [comment]
> I still don't exactly understand why keeping the default handler output to stdout is better than passing it to exit, giving more flexibility, but I think we'll return to this issue eventually.

@skejeton Passing it to `exit()` will result in printing two stack traces by the standalone Umka: one from where the `std.Err` was created, the other from where the `exit()` was called. It's somewhat confusing, though not a big problem for me. That's what I meant when I was asking you in the very beginning: 

> Do you think it's a lesser evil for now to sometimes have two stack traces than to have none?

**Comment by skejeton** [comment]
Having the stack trace be handled by the C code seems reasonable to me. Marek said:

> but what if the application wants to, for example, log it to a file and then call some other cleanup functions?

But that will remain to be the case for all existing tophat builds except for the Windows subsystem build, which has no `stdout`/`stderr` to speak of, so you can't even collect the logs from it.

**Comment by vtereshkov** [comment]
@skejeton What exactly is the standalone Umka behavior on your branch? Two stack traces? Is it OK for you? If it is and if it solves your original problem, I can approve your PR "as is" considering it as a temporary measure until we invent something better.

**Comment by skejeton** [comment]
Right now it is indeed 2 stack traces, but that was a mistake, it should just print the message, and let the C code handle printing of the stack trace. 

In other words, answering the question:

>  Do you think it's a lesser evil for now to sometimes have two stack traces than to have none?

Yes, although it's not none, it's just having one stack-trace, at least in our use cases since default Umka runtime already prints the stack-trace, and so does Tophat.

**Comment by vtereshkov** [comment]
@skejeton It's not a mistake, it's just a much bigger task to substitute the stack trace obtained from `umkaGetStack()` with the trace saved in `std.Err`. We're unable to do it now, as it requires a deeper integration between the `std.Err` and the interpreter internals.

So, do we merge what we have?

**Comment by skejeton** [comment]
In this case I'm fine if this is closed without a merge, since I can easily search and replace my codebase once there's a way to transfer stack traces between Umka and C. I'm ambivalent on this now. So it's up to you to decide.

**Comment by vtereshkov** [comment]
Merged as a temporary solution.

**Pull request merged**
